## Below are two functions that can creat a special object that can 
## caches the inverse of a matrix

## this function creats a "matrix" to cache both the imput matrix and 
## the inverse of imput matrix

makeCacheMatrix <- function(x = matrix()) {
        originmatrix <- x
        inverse <- solve(x)
        list(originmatrix = originmatrix,
                inverse = inverse)
}


## this function calculates the matrix generated by the upon function
## it will check whether the inverse had already been calculated, if
## not, an inverse of the imput matrix of upon function will return, 
## otherwise it will return the data in the cache

cacheSolve <- function(x, ...) {
        ## check the result of upon function 
        m <- x$inverse
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        ## Return a matrix that is the inverse of 'x'
        return(solve(x$originmatrix))
}
