## Below are two functions that can creat a special object that can 
## caches the inverse of a matrix

## this function creats a "matrix" to cache both the imput matrix and 
## the inverse of imput matrix

makeCacheMatrix <- function(x = matrix()) {
        m <- NULL
        set <- function(y) {
        x <<- y
        m <<- NULL
        }
        get <- function() x
        setmean <- function(solve) m <<- solve
        getmean <- function() m
        list(set = set, get = get,
        setsolve = setsolve,
        getsolve = getsolve)
}


## this function calculates the matrix generated by the upon function
## it will check whether the inverse had already been calculated, if
## not, an inverse of the imput matrix of upon function will return, 
## otherwise it will return the data in the cache

cacheSolve <- function(x, ...) {
        ## check the result of upon function 
        m <- x$getsolve()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        ## Return a matrix that is the inverse of 'x'
        data <- x$get()
        m <- solve(data, ...)
        x$setmean(m)
        m
}
